### ISSUE TITLE
Why the resize knob was removed ?

### ISSUE THREAD

**Issue by rabser** [geoffrowland/moodle-filter_jmol#13] opened 2015-02-13 09:35 UTC
It seems that the resize feature was removed in the commit 754e5e7c988805448c13a8f881bba22bc5ae478b

There is a reason for this removal ?

thanks in advance.

**Comment by geoffrowland** [comment] 2015-02-13 11:32
Hi Rabser

Apologies, a 'reversion' in my last update for Moodle 2.7/2.8. I'm approaching the end of a major 'refactor' of the Jmol filter which will restore the resize feature. Also add a 'fullscreen' feature.

One key underpinning change is that JSmol/Jmol/GLmol will now be contained in an iframe which will prevent 'clashes' with other JavaScript in the Moodle context and fix some long standing bugs/irritations e.g block docking, glossaries and MathJax. 

The forthcoming version will also support binary data structure files, e.g pdb.gz, .png (PNGJ) and pse on most/all recent browsers. Also, use delayApplet function so that an image is first loaded to speed up page load times. This works very nicely with the PNGJ format (stucture data + png image). In addition, some refinements to the default controls and menus. 

I hope to release this in the next few days/week.

So be patient ;-) . As ever, will be grateful for any feedback on the new version.

**Comment by rabser** [comment] 2015-02-13 11:54
Are you sure about the iframe choice ? It doesn't break the accessibility constraints ?
Btw, with the actual release i'd to remove parts of the new check about $yui_jsmol_has_been_configured or the question preview doesn't work.

One other thing that you could consider during the refactory, is the "enable/disable" of the download button (pretty simple to do) using the same way used for controls (es. ?d=0 at the end of the link).

For the MathJax problem, i've changed my code wrapping your code in an if-then-else with this condition:  ( typeof MathJax != 'undefined' ) so you can leave all uncommented and no changes to the code are required anymore if you have or not MathJax enabled...

hope this helps.

**Comment by geoffrowland** [comment] 2015-02-13 13:32
Not sure I understand the accessibility issues with an iframe. May be being dim!
The iframe 'sandboxes' the JSmol JavaScript, removes the need for YUI bundling and insulates JSmol from any other core Moodle JavaScript, MathJax or from 3rd-party modules etc. Also, removes the requirement for any of the '$yui_jsmol_has_been_configured' stuff, as JSmol will be loaded once only in each iframe (JSmol instance) - and not at all if there are no JSmol instances

The only issue I have encountered is that the JSmol right-click menu is contained within the iframe. However, the resizeable and fullscreen options, which work nicely with the iframe, provide a workaround for this. I'm also providing a smaller and simpler custom menus (including an option to open the full menu). Can also force the menu to open at the top-right corner of the iframe with some CSS.

I have always considered the presence of the download to be an important accessibility feature as if JSmol does not display,for whatever reason, the user can download the file and use a local viewer. I was also intending the new download link to default to the PNGJ format as this would encourage/facilitate conversion of resources to this format, which has a number of advantages and is becoming the default format for structure information. That said, I'll be happy to build  it into the ?c=0 confguration or add a new ?d=0 parameter if you have a good use case. Always happy to merge a good pull request! ;-)

The new version will also include dropdown controls for changing the JSmol background colour(white, grey and toggling between JSmol (default), GLmol (WebGL) and Jmol (Java) versions.

Thanks for the (typeof MathJax != 'undefined' ) condition tip. Should be very useful in any context where MathJax and JSmol can potentiallyclash (e.g. Mahara). Since MathJax now supports chemistry equations via the mhchem extension, there are many situations where JSmol and MathJax may be used together.

**Comment by rabser** [comment] 2015-02-13 13:55
The iframes are usually  considered harmful because lead to break the navigation flow inside the browser. They are often declared as deprecated by the web sites best practices.Even the Italian laws for institutional web sites accessibility do not permit the usage of the iframes. Maybe googling around you can get more precise information about it. I understand your position about the simplicity on embedding, but could be a jump back, not forward...

The use-case for disabling the download is this: if i'm using the filter to display a molecule as a part of a question, i would need to obscure (as better as i can) any information that can bring the student to catch "side" information, like the file name which is pretty available in the download link. For a better solution, the best would be to remove also the file->save menu item from the popup. 

I hope that my horrible english is clear enough.

**Comment by geoffrowland** [comment] 2015-02-13 15:46
Still not sure there is an issue with iframes. I fully appreciate that the frame and frameset elements have long been deprecated, for the reasons you describe, and are now obsolete in HTML5. 

However, it is my understanding that this is not the case for the iframe (inline frame) element, which is not the same as a frame (a common misconception) and remains part of the HTML5 standard. The iframe element does not replace the body of a page. It acts as a means to include a new browsing context embedded within a block of content. It does not suffer from the same usability or accessibility problems as the frameset model and can be used almost anywhere one needs to include an embedded browsing context. In this case it is simply inserting a minimal web page with the JSmol instance and associated JavaScript, much the same as embedding an image.

That said, I'm not an expert in Italian laws! :-(

Perhaps the ?c=0 (no controls) attribute should hide both the download link and Jmol help link? There's a certain logic to that. 

In an assessment context, you should also be able to completely turn off the popup menu with the Jmol script: set disablePopupMenu TRUE. The Jmol Wiki also has details on how to edit/load custom menus.

**Comment by rabser** [comment] 2015-02-13 15:54
iframe item: maybe the inlined iframe it's not a problem, but what about responsiveness ? if you shrink the browser does appear a second set of scrollbars ? Could be hard to use on mobiles.

controls: In my actual patch, i left separate the removal options, because the student should still need to interact with the molecule.

popup menu: i read about the jmol script, but our teachers are mainly biologists, not coders... :-)

**Comment by geoffrowland** [comment] 2015-02-13 16:54
In my hands, the iframe responsiveness seems good. No issue with scrollbars appearing as the JSmol object is sized as 100% inside the page, inside the iframe, so adapts to the size the iframe (as originally set, resized or fullscreen). The iframe content also has oveflow:hidden. Should work on any browser/device that supports iframes + JavaScript. The use of a cover image and delayApplet: true improves usability with mobiles/tablets. I'm experimenting with a control to change the JSmol platformSpeed to improve responsivenes on mobiles/platforms. 

I'm am considering an option to switch to the minimalist JSmolLite (TwirlyMol) for mobiles/tablets, but this currently only works with .mol/.sdf files and perhaps would be better as a separate TwirlyMol filter.

There is always a difficult balance between adding features for learning and hiding features for assessment in all possible use-cases. Appreciate things need to be as simple as possible for teachers!

**Comment by geoffrowland** [comment] 2015-02-13 18:50
I have just restored the YUI resizeable drag-handle. If it works for you, I'll close this issue.

**Comment by rabser** [comment] 2015-02-13 21:48
I can confirm that the resize feature works again. Thanks for your prompt effort.
Feel free to ask if you need anything.
Have a good we.

**Comment by geoffrowland** [comment] 2015-02-13 22:15
Hmm...

I'm still getting some clashes with MathJax with this version. Depends on the browser (particular JavaScrpit engines).

Of course, one workaround is to turn off the MathJax filter and use the TeX filter, but that's not ideal...

This was one of the 'drivers' for the move to the iframe 'container' which,in my hands, does seem to solve the problem in a robust way. I'll try to get a usable version of this out for testing ASAP.

That said, if you come up with alternativer solutions, I'll be more than happy to patch thingsin.

**Comment by rabser** [comment] 2015-02-13 22:31
I've MathJax enabled, and i didn't get any error, but...
i've disabled the if part   "&& !isset($yui_jsmol_has_been_configured)" around line 67, and the JS code at the end of filter.php was modified as follow:

        Y.on('load', function () {
            //Uncomment following if MathJax is installed
          if ( typeof MathJax != 'undefined' ) {
            MathJax.Hub.Queue(function () {
                Jmol.setDocument(0);
                Jmol._alertNoBinary = false;
                Jmol._tracker = undefined;
                Jmol.getApplet('jmol".$id."', Info);
                $('#jmoldiv".$id."').html(Jmol.getAppletHtml(jmol".$id."));
                $('#control".$id."').html(".$control.");
            });
          } else {
                        Jmol.setDocument(0);
                        Jmol._alertNoBinary = false;
                        Jmol._tracker = undefined;
                        Jmol.getApplet('jmol".$id."', Info);
                        $('#jmoldiv".$id."').html(Jmol.getAppletHtml(jmol".$id."));
                        $('#control".$id."').html(".$control.");
          }
        });
    });

Maybe it's useful to solve these clashes too..

**Comment by geoffrowland** [comment] 2015-02-14 00:39
Thanks, that's the same code that I tried from your earlier note. I have tried both the !== and != operators with no noticeable difference. Will be happy to merge this . Thanks again!

In my hands this works consistently well with Firefox. However, Chrome and Opera still throw up MathJax errors (red ! instead of equation) some of the time on page refresh.  The problem is more evident with mutliple Jmol instances in a Moodle course. All browsers are up-to-date versions on Fedora 21 Linux.

I'm testing with the MathJax CDN on Moodle 2.7 with MathJax (or the Tex filter) at the top of the filter list (above the Jmol/Jsmol filter).

I'm also still finding Moodle block-docking (problem with YUI rollup? does not work  in courses with a JSmol instance (conflict with YUI rollup?). I'm using Essential theme. Does this work for you?

**Comment by rabser** [comment] 2015-02-14 16:10
Sigh, i can confirm that with the theme "more" the docking fails even with a single molecule in page.
The mathjax problem seems like a race-condition, if it depends on the page refresh/reload, it's likely to be something connected to load sequence of YUI or similar. Maybe the two symptoms are connected.
I'll try to debug around...

**Comment by geoffrowland** [comment] 2015-09-11 06:05
Should now be fixed with latest master branch. JSmol contained in resizeable iframe. Also, full-screen display.

**Closed by geoffrowland** 2015-09-11 06:05 UTC
